id: validate_rh_clean
namespace: sports_events

inputs:
  - id: rh_clean_file
    type: STRING

tasks:
  - id: validate_rh
    type: io.kestra.plugin.scripts.python.Script
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      image: ghcr.io/kestra-io/pydata:latest
    beforeCommands:
      - pip install --no-cache-dir pandas boto3
        
    script: |
      import pandas as pd
      import boto3
      s3 = boto3.client("s3",aws_access_key_id="redacted",aws_secret_access_key="redacted",region_name="eu-west-3")

      s3.download_file("sport-data-raw", "curated/dim/DIM_employees.csv", "/tmp/rh.csv")
    
      df = pd.read_csv("/tmp/rh.csv")

      # employee_id
      assert df["employee_id"].notnull().all(), "employee_id contains nulls"
      assert df["employee_id"].is_unique, "employee_id is not unique"

      # type_contrat
      assert df["type_contrat"].isin(["CDI", "CDD"]).all(), "Invalid type_contrat found"

      # salarie_brut
      assert (df["salarie_brut"] > 0).all(), "Invalid salarie_brut: must be > 0"

      # distance_domicile
      assert(df["distance_domicile_km"] > 0).all(), "Invalid distance: must be > 0"

      # jours_cp
      assert (df["jours_cp"] > 0).all(), "Invalid jours_cp: must be > 0"

      # moyen_deplacement normalized
      valid_moves = [
          "transports_en_commun",
          "vehicule_thermique_electrique",
          "marche_running",
          "velo_trottinette_autres"
      ]
      assert df["moyen_deplacement"].isin(valid_moves).all(), "Invalid moyen_deplacement values"

      # date fields
      pd.to_datetime(df["date_naissance"], errors="raise")
      pd.to_datetime(df["date_embauche"], errors="raise")

      print("RH validation passed successfully")

triggers:
  - id: trigger_after_clean_rh
    type: io.kestra.plugin.core.trigger.Flow
    preconditions:
      id: clean_rh_done
      flows:
        - namespace: sports_events
          flowId: curated_dim_employees
          states:
            - SUCCESS
            - WARNING
    inputs: {}
